version: "3"

services:
  blogpy_postgresql:
    image: postgres:alpine
    container_name: blogpy_postgresql
    volumes:
      - type: 'bind'
        source: ./blogpy_postgresql
        target: /var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - blogpy_network

volumes:
  blogpy_postgresql:
    external: true

networks:
  blogpy_network:
    external: true